<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 14-12-16
 * Time: 上午9:50
 */

return array(
    'di'=>array(
        'Fish\Model\NewsTable'=>'Fish\Model\NewsTable',
        'Fish\Model\ImgTable' =>'Fish\Model\ImgTable',
        'Fish\Model\NoticeTable'=>'Fish\Model\NoticeTable',
        'Fish\Model\ArticleTable'=>'Fish\Model\ArticleTable',
        'Fish\Model\CommonImgTable'=>'Fish\Model\CommonImgTable',
        'Fish\Model\FoodTable'=>'Fish\Model\FoodTable',
    ),
    'router'=>array(
        'routes'=>array(
            'Fish_show_all'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/home',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\ShowNewsController',
                    )
                ),
            ),
            'Fish_create_news'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/news/create',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\SendNewsController',
                    )
                ),
            ),
            'Fish_delete_news'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/delete/news[/:id]',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\DeleteNewsController',
                    )
                ),
            ),
            'Fish_create_notice'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/notice/create',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\SendNoticeController',
                    )
                ),
            ),
            'Fish_show_notice'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/notice',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\ShowNoticeController',
                    )
                ),
            ),
            'Fish_delete_notice'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/delete/notice[/:id]',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\DeleteNoticeController',
                    )
                ),
            ),

            'Fish_create_article'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/article/create',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\SendArticleController',
                    )
                ),
            ),
            'Fish_show_article'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/article',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\ShowArticleController',
                    )
                ),
            ),
            'Fish_delete_article'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/delete/article[/:id]',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\DeleteArticleController',
                    )
                ),
            ),

            'Fish_create_img'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/img/create',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\SendImgController',
                    )
                ),
            ),
            'Fish_show_img'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/img',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\ShowImgController',
                    )
                ),
            ),
            'Fish_delete_img'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/delete/img[/:id]',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\DeleteImgController',
                    )
                ),
            ),

            'Fish_create_food'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/food/create',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\SendFoodController',
                    )
                ),
            ),
            'Fish_show_food'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/food',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\ShowFoodController',
                    )
                ),
            ),
            'Fish_delete_food'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/delete/food[/:id]',
                    'defaults'=>array(
                        'controller'=>'Fish\Controller\DeleteFoodController',
                    )
                ),
            ),

        ),
    ),

    'controllers'=>array(
        'invokables'=>array(
            'Fish\Controller\ShowNewsController'=>'Fish\Controller\ShowNewsController',
            'Fish\Controller\SendNewsController'=>'Fish\Controller\SendNewsController',
            'Fish\Controller\DeleteNewsController'=>'Fish\Controller\DeleteNewsController',
            'Fish\Controller\ShowNoticeController'=>'Fish\Controller\ShowNoticeController',
            'Fish\Controller\SendNoticeController'=>'Fish\Controller\SendNoticeController',
            'Fish\Controller\DeleteNoticeController'=>'Fish\Controller\DeleteNoticeController',
            'Fish\Controller\ShowArticleController'=>'Fish\Controller\ShowArticleController',
            'Fish\Controller\ShowFoodController'=>'Fish\Controller\ShowFoodController',
            'Fish\Controller\ShowImgController'=>'Fish\Controller\ShowImgController',

        ),
    ),
);