
news<br/>
<?php
    foreach($newsData as $v){
        echo $v->getNewsName().'<br/>';
        foreach($imgData as $v1){
            if($v->getId()==$v1->getImgNewsId())
            {
                $temp = substr($v1->getImgUrlMax(),7);
                echo "<img src=\"".$temp."\">".'<br/>';
            }
        }
    }
?>
<br/>
<br/>
notice<br/>
<?php
    foreach($noticeData as $v){
        echo $v->getNoticeName().'___';
        echo $v->getNoticeContent().'___';
        echo $v->getNoticeEditor().'___';
        echo $v->getNoticeDate();
        echo '<br/>';
        }
?>
<br/>
article
<br/>
<?php
foreach($articleData as $v){
    echo $v->getArticleName().'___';
    echo $v->getArticleContent().'___';
    echo $v->getArticleEditor().'___';
    echo $v->getArticleDate();
    echo '<br/>';
}
?>

<br/>
food
<br/>
<?php
foreach($foodData as $v){
    echo $v->getFoodName().'___';
    echo $v->getFoodIntro().'___';
    echo $v->getFoodDate().'___';
    echo '<br/>';
    $temp = substr($v->getFoodImgMax(),7);
    echo "<img src=\"".$temp."\">".'<br/>';
}
?>

<br/>
img
<br/>
<?php
foreach($commonImgData as $v){
    echo $v->getImgName().'___';
    echo $v->getImgIntro().'___';
    echo '<br/>';
    $temp = substr($v->getImgUrlMax(),7);
    echo "<img src=\"".$temp."\">".'<br/>';
}
?>
<?php
$temp = dirname(__FILE__);
$temp1 = substr($temp,0,23);

?>
